import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const LAST_UPDATED = "February 13, 2026";

export default function Terms() {
  return (
    <div className="min-h-screen gentle-bg">
      <div className="max-w-3xl mx-auto px-5 sm:px-6 py-10 sm:py-14">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-[#5C7A6A] hover:text-[#849D8E] mb-6"
          data-testid="terms-back-link"
        >
          <ArrowLeft size={14} /> Back to SA Coparents
        </Link>

        <div className="eyebrow mb-3">Terms of Service</div>
        <h1 className="font-serif text-3xl sm:text-4xl text-[#2A3631] mb-2 leading-tight">
          Plain-English terms.
        </h1>
        <p className="text-sm text-[#8A9A92] mb-8">Last updated: {LAST_UPDATED}</p>

        <Prose>
          <p>
            Welcome to <strong>SA Coparents</strong> ("we", "us"). By creating an
            account or using the app, you agree to these Terms.
            If you don't agree, please don't use the app.
          </p>

          <H2>1. What this app is — and isn't</H2>
          <p>
            SA Coparents is a <strong>preparation tool</strong> for parents heading into a co-parenting mediation session. It helps you organize your thoughts, identify priorities, and arrive at mediation calm and child-centered.
          </p>
          <p>
            SA Coparents is <strong>NOT</strong>:
          </p>
          <ul>
            <li>Legal advice or a substitute for an attorney</li>
            <li>Mental-health treatment or a substitute for therapy</li>
            <li>An official legal document — the "Co-Parenting Agreement Draft" is a starter document only and has no legal force until reviewed, edited, and signed under proper legal guidance</li>
            <li>Crisis intervention — if you are in danger, call 911 or the National Domestic Violence Hotline (1-800-799-7233). For mental-health crisis, call 988.</li>
          </ul>

          <H2>2. Your account</H2>
          <p>
            You're responsible for keeping your password secure and for everything that happens under your account. You agree not to share your account with anyone else. If you suspect unauthorized access, email us immediately.
          </p>
          <p>
            You must be 18 or older to create an account. The app is intended for parents and is not directed at children.
          </p>

          <H2>3. Acceptable use</H2>
          <p>You agree NOT to:</p>
          <ul>
            <li>Use the app to harass, threaten, or harm another person (including your co-parent or child)</li>
            <li>Misrepresent your identity to mislead a mediator or court</li>
            <li>Attempt to reverse-engineer, scrape, overload, or break into the app</li>
            <li>Use the app to share content that is unlawful, defamatory, or violates someone else's rights</li>
            <li>Use any automation, bots, or AI agents to interact with the app on your behalf without permission</li>
          </ul>
          <p>We may suspend or terminate accounts that violate these rules.</p>

          <H2>4. Your content stays yours</H2>
          <p>
            Everything you type into the app — goals, concerns, priorities, communication notes, readiness ratings — belongs to you. We don't claim ownership.
          </p>
          <p>
            You grant us a limited, non-exclusive license to host, process, transmit, and use your content <strong>solely to provide the app's features</strong>: storing your prep, generating your summaries via AI, emailing PDFs to your mediator at your request, and so on. We may not use your content for advertising, training AI models, or any other purpose.
          </p>

          <H2>5. AI-generated documents</H2>
          <p>
            Your Mediation Summary, Co-Parenting Agreement Draft, and Things I Can Improve On plan are generated by an AI model (Anthropic Claude) using your prep data. These documents are intended as a <strong>starting point for conversation</strong>, not legally binding agreements or professional advice.
          </p>
          <p>
            AI can make mistakes. Always read what's generated, edit it as needed, and consult a mediator or attorney before relying on any of it.
          </p>

          <H2>6. Sharing and email features</H2>
          <p>
            When you use the "Share via text" or "Email to mediator" features, you are responsible for whom you share with and what you share. We do not endorse, vet, or have a relationship with any mediator or other third party you choose.
          </p>
          <p>
            Shared download links expire automatically after 7 days for your protection.
          </p>

          <H2>7. Service availability</H2>
          <p>
            We work hard to keep the app available, but we don't guarantee uninterrupted access. We may pause, update, or discontinue features without prior notice — though we'll do our best to communicate significant changes in advance.
          </p>

          <H2>8. Disclaimer of warranties</H2>
          <p>
            The app is provided "as is" and "as available". To the maximum extent permitted by law, we disclaim all warranties — express, implied, or statutory — including warranties of merchantability, fitness for a particular purpose, accuracy, and non-infringement.
          </p>
          <p>
            We make no warranty that the AI-generated documents will be accurate, complete, suitable for your situation, or legally enforceable.
          </p>

          <H2>9. Limitation of liability</H2>
          <p>
            To the maximum extent permitted by law, we will not be liable for indirect, incidental, special, consequential, or punitive damages (including lost profits, lost data, or emotional distress) arising from your use of the app — even if we've been advised of the possibility.
          </p>
          <p>
            Our total liability for any claim related to the app will not exceed the greater of (a) the amount you've paid us in the past 12 months or (b) $100.
          </p>

          <H2>10. Indemnification</H2>
          <p>
            You agree to defend and indemnify us against claims arising from (a) your misuse of the app, (b) content you submit, or (c) your violation of these Terms or someone else's rights.
          </p>

          <H2>11. Termination</H2>
          <p>
            You may delete your account at any time by emailing us. We may suspend or terminate your access if you violate these Terms or use the app in a way that harms others.
          </p>
          <p>
            Sections about disclaimers, limitation of liability, and indemnification survive termination.
          </p>

          <H2>12. Changes to these Terms</H2>
          <p>
            We may update these Terms occasionally. If changes are material (e.g., new restrictions on use), we'll email you before they take effect.
          </p>

          <H2>13. Governing law</H2>
          <p>
            These Terms are governed by the laws of the State of Texas, without regard to conflict-of-laws principles. Any dispute will be resolved exclusively in the state or federal courts located in Bexar County, Texas.
          </p>

          <H2>14. Contact</H2>
          <p>
            Email <a href="mailto:mattsossi@bsossi.com" className="text-[#5C7A6A] underline">mattsossi@bsossi.com</a>
            {" "}or call <a href="tel:2102241667" className="text-[#5C7A6A] underline">210-224-1667</a>.
          </p>
          <p className="text-xs text-[#8A9A92] italic mt-8">
            SA Coparents · 16607 Blanco #703, San Antonio, Texas 78232
          </p>
        </Prose>
      </div>
    </div>
  );
}

function H2({ children }) {
  return (
    <h2 className="font-serif text-2xl text-[#2A3631] mt-10 mb-3">{children}</h2>
  );
}

function Prose({ children }) {
  return (
    <div className="prose-soft space-y-3 text-[#2A3631] leading-relaxed [&_p]:text-[#5C6B64] [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_li]:text-[#5C6B64] [&_strong]:text-[#2A3631] text-[15px]">
      {children}
    </div>
  );
}
